"""create initial v1 schema

Revision ID: 954cafea46eb
Revises:
Create Date: 2026-08-26 15:16:03.432813
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "954cafea46eb"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workflow", sa.Text(), nullable=False),
        sa.Column("step", sa.Text(), nullable=False),
        sa.Column("parent_run_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("model_id", sa.Text(), nullable=False),
        sa.Column("prompt_version", sa.Text(), nullable=False),
        sa.Column("schema_version", sa.Text(), nullable=False),
        sa.Column("redacted_input", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("redacted_output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "source_manifest",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("estimated_cost_usd", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retry_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'succeeded', 'failed', 'invalid')",
            name=op.f("ck_ai_runs_status_values"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_run_id"],
            ["ai_runs.id"],
            name=op.f("fk_ai_runs_parent_run_id_ai_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_runs")),
    )
    op.create_table(
        "app_settings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("singleton_key", sa.SmallInteger(), server_default="1", nullable=False),
        sa.Column(
            "role_types",
            sa.ARRAY(sa.Text()),
            server_default="{internship,new_grad,entry_level}",
            nullable=False,
        ),
        sa.Column("keywords", sa.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("excluded_keywords", sa.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("preferred_locations", sa.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("remote_preference", sa.Text(), server_default="any", nullable=False),
        sa.Column(
            "notify_current_jobs_on_save",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "email_notifications_enabled",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("notification_email", sa.Text(), nullable=True),
        sa.Column("timezone", sa.Text(), server_default="America/New_York", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "remote_preference IN ('any', 'remote', 'hybrid', 'onsite')",
            name=op.f("ck_app_settings_remote_preference_values"),
        ),
        sa.CheckConstraint("singleton_key = 1", name=op.f("ck_app_settings_singleton_key_one")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_settings")),
        sa.UniqueConstraint("singleton_key", name="uq_app_settings_singleton"),
    )
    op.create_table(
        "companies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("canonical_name", sa.Text(), nullable=False),
        sa.Column("normalized_name", sa.Text(), nullable=False),
        sa.Column("official_domain", sa.Text(), nullable=False),
        sa.Column("official_website_url", sa.Text(), nullable=False),
        sa.Column("headquarters_country", sa.String(length=2), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("verification_status", sa.Text(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "verification_status IN ('proposed', 'verified', 'rejected')",
            name=op.f("ck_companies_verification_status_values"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
        sa.UniqueConstraint("official_domain", name=op.f("uq_companies_official_domain")),
    )
    op.create_index(
        op.f("ix_companies_normalized_name"), "companies", ["normalized_name"], unique=False
    )
    op.create_table(
        "immigration_dataset_imports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("dataset_type", sa.Text(), nullable=False),
        sa.Column("fiscal_year", sa.SmallInteger(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("record_layout_version", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("rows_read", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("rows_accepted", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "dataset_type = 'dol_lca'",
            name=op.f("ck_immigration_dataset_imports_dataset_type_values"),
        ),
        sa.CheckConstraint(
            "status IN ('running', 'succeeded', 'failed')",
            name=op.f("ck_immigration_dataset_imports_status_values"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_immigration_dataset_imports")),
        sa.UniqueConstraint(
            "dataset_type",
            "fiscal_year",
            "source_sha256",
            name=op.f("uq_immigration_dataset_imports_dataset_type"),
        ),
    )
    op.create_table(
        "industry_queries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("raw_query", sa.Text(), nullable=False),
        sa.Column("normalized_query", sa.Text(), nullable=False),
        sa.Column("country_code", sa.String(length=2), server_default="US", nullable=False),
        sa.Column("interpretation_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("prompt_version", sa.Text(), nullable=False),
        sa.Column("model_id", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'succeeded', 'failed')",
            name=op.f("ck_industry_queries_status_values"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_industry_queries")),
    )
    op.create_index(
        op.f("ix_industry_queries_normalized_query"),
        "industry_queries",
        ["normalized_query"],
        unique=False,
    )
    op.create_table(
        "notification_outbox",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("channel", sa.Text(), nullable=False),
        sa.Column("event_group_key", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provider_message_id", sa.Text(), nullable=True),
        sa.Column("last_error_code", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "channel IN ('in_app', 'email')", name=op.f("ck_notification_outbox_channel_values")
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'sending', 'sent', 'failed', 'cancelled')",
            name=op.f("ck_notification_outbox_status_values"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_outbox")),
        sa.UniqueConstraint(
            "channel", "event_group_key", name=op.f("uq_notification_outbox_channel")
        ),
    )
    op.create_table(
        "owner_profile",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("singleton_key", sa.SmallInteger(), server_default="1", nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("country_code", sa.String(length=2), server_default="US", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("singleton_key = 1", name=op.f("ck_owner_profile_singleton_key_one")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_owner_profile")),
        sa.UniqueConstraint("singleton_key", name="uq_owner_profile_singleton"),
    )
    op.create_table(
        "career_sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("careers_url", sa.Text(), nullable=False),
        sa.Column("canonical_source_key", sa.Text(), nullable=False),
        sa.Column(
            "provider_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("poll_interval_minutes", sa.Integer(), server_default="60", nullable=False),
        sa.Column("next_poll_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_owner", sa.Text(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("etag", sa.Text(), nullable=True),
        sa.Column("last_modified", sa.Text(), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "provider IN ('greenhouse', 'lever', 'ashby', 'generic_html', 'unsupported')",
            name=op.f("ck_career_sources_provider_values"),
        ),
        sa.CheckConstraint(
            "status IN ('pending_resolution', 'supported', 'degraded', 'unsupported', 'paused')",
            name=op.f("ck_career_sources_status_values"),
        ),
        sa.CheckConstraint(
            "poll_interval_minutes >= 15", name=op.f("ck_career_sources_poll_interval_minimum")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_career_sources_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_career_sources")),
        sa.UniqueConstraint(
            "canonical_source_key", name=op.f("uq_career_sources_canonical_source_key")
        ),
    )
    op.create_index(
        op.f("ix_career_sources_lease_expires_at"),
        "career_sources",
        ["lease_expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_career_sources_next_poll_at"), "career_sources", ["next_poll_at"], unique=False
    )
    op.create_table(
        "company_aliases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("alias", sa.Text(), nullable=False),
        sa.Column("normalized_alias", sa.Text(), nullable=False),
        sa.Column("alias_type", sa.Text(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "alias_type IN ('brand', 'former_name', 'subsidiary', 'abbreviation')",
            name=op.f("ck_company_aliases_alias_type_values"),
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_company_aliases_confidence_range")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_company_aliases_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_aliases")),
        sa.UniqueConstraint(
            "company_id", "normalized_alias", name=op.f("uq_company_aliases_company_id")
        ),
    )
    op.create_table(
        "company_evidence",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("evidence_type", sa.Text(), nullable=False),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("source_title", sa.Text(), nullable=True),
        sa.Column("exact_quote", sa.Text(), nullable=True),
        sa.Column("source_domain", sa.Text(), nullable=False),
        sa.Column("is_official_source", sa.Boolean(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.CheckConstraint(
            "evidence_type IN ('industry', 'official_identity', 'careers_page', 'internship_program', 'cpt', 'work_authorization')",
            name=op.f("ck_company_evidence_evidence_type_values"),
        ),
        sa.CheckConstraint(
            "status IN ('supports', 'conflicts', 'unknown')",
            name=op.f("ck_company_evidence_status_values"),
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_company_evidence_confidence_range")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_company_evidence_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_evidence")),
    )
    op.create_table(
        "company_industries",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("industry_slug", sa.Text(), nullable=False),
        sa.Column("industry_label", sa.Text(), nullable=False),
        sa.Column("relevance_score", sa.SmallInteger(), nullable=False),
        sa.Column("evidence_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "relevance_score >= 0 AND relevance_score <= 100",
            name=op.f("ck_company_industries_relevance_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_company_industries_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("company_id", "industry_slug", name=op.f("pk_company_industries")),
    )
    op.create_table(
        "company_legal_entities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("legal_name", sa.Text(), nullable=False),
        sa.Column("normalized_legal_name", sa.Text(), nullable=False),
        sa.Column("match_method", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("evidence_url", sa.Text(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "match_method IN ('exact', 'ai_proposed', 'owner_verified')",
            name=op.f("ck_company_legal_entities_match_method_values"),
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_company_legal_entities_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_company_legal_entities_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_legal_entities")),
        sa.UniqueConstraint(
            "company_id", "normalized_legal_name", name=op.f("uq_company_legal_entities_company_id")
        ),
    )
    op.create_index(
        op.f("ix_company_legal_entities_normalized_legal_name"),
        "company_legal_entities",
        ["normalized_legal_name"],
        unique=False,
    )
    op.create_table(
        "discovery_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("industry_query_id", sa.UUID(), nullable=True),
        sa.Column("raw_query", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'succeeded', 'failed')",
            name=op.f("ck_discovery_runs_status_values"),
        ),
        sa.ForeignKeyConstraint(
            ["industry_query_id"],
            ["industry_queries.id"],
            name=op.f("fk_discovery_runs_industry_query_id_industry_queries"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discovery_runs")),
    )
    op.create_index(
        op.f("ix_discovery_runs_industry_query_id"),
        "discovery_runs",
        ["industry_query_id"],
        unique=False,
    )
    op.create_table(
        "in_app_notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("outbox_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("action_url", sa.Text(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["outbox_id"],
            ["notification_outbox.id"],
            name=op.f("fk_in_app_notifications_outbox_id_notification_outbox"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_in_app_notifications")),
        sa.UniqueConstraint("outbox_id", name=op.f("uq_in_app_notifications_outbox_id")),
    )
    op.create_table(
        "lca_employer_yearly_stats",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("dataset_import_id", sa.UUID(), nullable=False),
        sa.Column("fiscal_year", sa.SmallInteger(), nullable=False),
        sa.Column("legal_employer_name", sa.Text(), nullable=False),
        sa.Column("normalized_legal_employer_name", sa.Text(), nullable=False),
        sa.Column("certified_cases", sa.Integer(), server_default="0", nullable=False),
        sa.Column("certified_workers", sa.Integer(), server_default="0", nullable=False),
        sa.Column("denied_cases", sa.Integer(), server_default="0", nullable=False),
        sa.Column("withdrawn_cases", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "top_occupations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "certified_cases >= 0",
            name=op.f("ck_lca_employer_yearly_stats_certified_cases_nonnegative"),
        ),
        sa.CheckConstraint(
            "certified_workers >= 0",
            name=op.f("ck_lca_employer_yearly_stats_certified_workers_nonnegative"),
        ),
        sa.CheckConstraint(
            "denied_cases >= 0", name=op.f("ck_lca_employer_yearly_stats_denied_cases_nonnegative")
        ),
        sa.CheckConstraint(
            "withdrawn_cases >= 0",
            name=op.f("ck_lca_employer_yearly_stats_withdrawn_cases_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_import_id"],
            ["immigration_dataset_imports.id"],
            name=op.f("fk_lca_employer_yearly_stats_dataset_import_id_immigration_dataset_imports"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lca_employer_yearly_stats")),
        sa.UniqueConstraint(
            "dataset_import_id",
            "normalized_legal_employer_name",
            name=op.f("uq_lca_employer_yearly_stats_dataset_import_id"),
        ),
    )
    op.create_index(
        op.f("ix_lca_employer_yearly_stats_normalized_legal_employer_name"),
        "lca_employer_yearly_stats",
        ["normalized_legal_employer_name"],
        unique=False,
    )
    op.create_table(
        "saved_companies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("baseline_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "notify_current_jobs", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'paused')", name=op.f("ck_saved_companies_status_values")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_saved_companies_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saved_companies")),
        sa.UniqueConstraint("company_id", name=op.f("uq_saved_companies_company_id")),
    )
    op.create_table(
        "discovery_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("discovery_run_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("rank", sa.SmallInteger(), nullable=False),
        sa.Column("opportunity_score", sa.SmallInteger(), nullable=False),
        sa.Column("industry_score", sa.SmallInteger(), nullable=False),
        sa.Column("sponsorship_score", sa.SmallInteger(), nullable=False),
        sa.Column("internship_score", sa.SmallInteger(), nullable=False),
        sa.Column("monitorability_score", sa.SmallInteger(), nullable=False),
        sa.Column("current_openings_score", sa.SmallInteger(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("is_hidden", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "current_openings_score BETWEEN 0 AND 100",
            name=op.f("ck_discovery_results_current_openings_score_range"),
        ),
        sa.CheckConstraint(
            "industry_score BETWEEN 0 AND 100",
            name=op.f("ck_discovery_results_industry_score_range"),
        ),
        sa.CheckConstraint(
            "internship_score BETWEEN 0 AND 100",
            name=op.f("ck_discovery_results_internship_score_range"),
        ),
        sa.CheckConstraint(
            "monitorability_score BETWEEN 0 AND 100",
            name=op.f("ck_discovery_results_monitorability_score_range"),
        ),
        sa.CheckConstraint(
            "opportunity_score BETWEEN 0 AND 100",
            name=op.f("ck_discovery_results_opportunity_score_range"),
        ),
        sa.CheckConstraint(
            "sponsorship_score BETWEEN 0 AND 100",
            name=op.f("ck_discovery_results_sponsorship_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_discovery_results_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["discovery_run_id"],
            ["discovery_runs.id"],
            name=op.f("fk_discovery_results_discovery_run_id_discovery_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discovery_results")),
        sa.UniqueConstraint(
            "discovery_run_id", "company_id", name="uq_discovery_results_run_company"
        ),
        sa.UniqueConstraint("discovery_run_id", "rank", name="uq_discovery_results_run_rank"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("career_source_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("external_job_id", sa.Text(), nullable=True),
        sa.Column("canonical_job_key", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("location_text", sa.Text(), nullable=True),
        sa.Column("department", sa.Text(), nullable=True),
        sa.Column("employment_type", sa.Text(), nullable=True),
        sa.Column("role_type", sa.Text(), nullable=False),
        sa.Column("description_text", sa.Text(), server_default="", nullable=False),
        sa.Column("apply_url", sa.Text(), nullable=False),
        sa.Column("source_posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("current_content_hash", sa.String(length=64), nullable=False),
        sa.Column("consecutive_absences", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role_type IN ('internship', 'new_grad', 'entry_level', 'experienced', 'unknown')",
            name=op.f("ck_jobs_role_type_values"),
        ),
        sa.CheckConstraint("status IN ('active', 'closed')", name=op.f("ck_jobs_status_values")),
        sa.ForeignKeyConstraint(
            ["career_source_id"],
            ["career_sources.id"],
            name=op.f("fk_jobs_career_source_id_career_sources"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_jobs_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint(
            "career_source_id", "canonical_job_key", name=op.f("uq_jobs_career_source_id")
        ),
    )
    op.create_table(
        "source_poll_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("career_source_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("jobs_received", sa.Integer(), server_default="0", nullable=False),
        sa.Column("jobs_created", sa.Integer(), server_default="0", nullable=False),
        sa.Column("jobs_updated", sa.Integer(), server_default="0", nullable=False),
        sa.Column("jobs_closed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('running', 'succeeded', 'partial', 'failed', 'not_modified')",
            name=op.f("ck_source_poll_runs_status_values"),
        ),
        sa.ForeignKeyConstraint(
            ["career_source_id"],
            ["career_sources.id"],
            name=op.f("fk_source_poll_runs_career_source_id_career_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_poll_runs")),
    )
    op.create_table(
        "job_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("poll_run_id", sa.UUID(), nullable=False),
        sa.Column("event_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dedupe_key", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "event_type IN ('discovered', 'updated', 'closed', 'reopened')",
            name=op.f("ck_job_events_event_type_values"),
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_job_events_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["poll_run_id"],
            ["source_poll_runs.id"],
            name=op.f("fk_job_events_poll_run_id_source_poll_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_events")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_job_events_dedupe_key")),
    )
    op.create_table(
        "job_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("poll_run_id", sa.UUID(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("normalized_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_job_snapshots_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["poll_run_id"],
            ["source_poll_runs.id"],
            name=op.f("fk_job_snapshots_poll_run_id_source_poll_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_snapshots")),
        sa.UniqueConstraint("job_id", "content_hash", name=op.f("uq_job_snapshots_job_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job_snapshots")
    op.drop_table("job_events")
    op.drop_table("source_poll_runs")
    op.drop_table("jobs")
    op.drop_table("discovery_results")
    op.drop_table("saved_companies")
    op.drop_index(
        op.f("ix_lca_employer_yearly_stats_normalized_legal_employer_name"),
        table_name="lca_employer_yearly_stats",
    )
    op.drop_table("lca_employer_yearly_stats")
    op.drop_table("in_app_notifications")
    op.drop_index(op.f("ix_discovery_runs_industry_query_id"), table_name="discovery_runs")
    op.drop_table("discovery_runs")
    op.drop_index(
        op.f("ix_company_legal_entities_normalized_legal_name"), table_name="company_legal_entities"
    )
    op.drop_table("company_legal_entities")
    op.drop_table("company_industries")
    op.drop_table("company_evidence")
    op.drop_table("company_aliases")
    op.drop_index(op.f("ix_career_sources_next_poll_at"), table_name="career_sources")
    op.drop_index(op.f("ix_career_sources_lease_expires_at"), table_name="career_sources")
    op.drop_table("career_sources")
    op.drop_table("owner_profile")
    op.drop_table("notification_outbox")
    op.drop_index(op.f("ix_industry_queries_normalized_query"), table_name="industry_queries")
    op.drop_table("industry_queries")
    op.drop_table("immigration_dataset_imports")
    op.drop_index(op.f("ix_companies_normalized_name"), table_name="companies")
    op.drop_table("companies")
    op.drop_table("app_settings")
    op.drop_table("ai_runs")
    # ### end Alembic commands ###
